# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: macos-latest
 
  jobs:

  - task: Npm@1
    displayName: npm install
    inputs:
      verbose: false
  - task: CmdLine@2
    displayName: Check Cypress Installed
    inputs:
      script: npx cypress verify


  - task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run test'
  continueOnError: true

  -task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '*.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/cypress/reports/junit'
    mergeTestResults: true
    testRunTitle: 'Publish Test Results'